### ISSUE TITLE
Test has started to fail

### ISSUE THREAD

**Issue by andk** [michal-josef-spacek/Plack-App-Tags-HTML#1]
Same perl with pass and with fail. The fail happened after I installed Plack::Component::Tags::HTML 0.06:

PASS: http://www.cpantesters.org/cpan/report/b67aba94-d331-11ec-bb21-a0f230a20789
FAIL: http://www.cpantesters.org/cpan/report/dbec6702-0926-11ed-a337-d51d46d06eb9

**Comment by michal-josef-spacek** [comment]
@andk This is incomatible change in Tags::HTML::Page::Begin, where i added <viewport>. Still i will look to it.

**Comment by michal-josef-spacek** [comment]
Fixed in 0.06 version
